media_folder: static/assets
public_folder: assets
public_folder_relative: false
collections:
  - name: books
    label: Books
    folder: src/content/books
    create: true
    slug: "{{authorLastname}}-{{title}}"
    fields:
      - { name: templateKey, label: "Template Key", widget: hidden, default: book }
      - { name: title, label: Title }
      - { name: authorLastname, label: "Primary Author Last Name" }
      - { name: author, label: "Author(s)" }
      - { name: cover, label: Cover, widget: image }
      - { name: description, label: Description }
      - { name: orderOnPage, label: "Order on Front Page", widget: number }
      - { name: readLink, label: "Read Link" }
      - { name: buyLink, label: "Buy Link" }
  - name: pages
    label: Pages
    files:
      - file: src/content/home.md
        name: home
        label: Home
        editor:
          preview: false
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: home-page }
          - name: taglineSection
            label: "Tag Line Section"
            widget: object
            fields:
              - { name: text, label: Text, widget: markdown }
          - name: callToActionSection
            label: "Call to Action Section"
            widget: object
            fields:
              - { name: description, label: Description }
              - { name: buttonUrl, label: "Button URL" }
              - { name: buttonLabel, label: "Button Label" }
      - file: "src/content/about.md"
        name: about
        label: About
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: about-page }
          - { name: title, label: About }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/authors.md"
        name: authors
        label: Authors
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: authors-page }
          - { name: title, label: Authors }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/contact.md"
        name: contact
        label: Contact
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: contact-page }
          - { name: title, label: Contact }
          - { name: body, label: Body, widget: markdown }
